function img_width(){if(($('#page-site-index').length>0)||($('#page-course-index').length>0)){max_width=$('.summary').width()-5;$('.summary img').each(function(){if($(this).width()>max_width){$(this).attr('width','').attr('height','').css('max-width',max_width+'px')}})}}
requirejs(['jquery'],function($){$(document).ready(function(){img_width();$('.expandteachers').addClass('expandteachers_vis')});$(window).resize(function(){img_width()});$(window).on('load',function(){if(($('#page-site-index').length>0)&&($(window).width()>1023)){$('.summary').each(function(){if($(this).children('.courseimage').length>0){var ciw=$(this).children('.courseimage').width()+10;$(this).css('width','calc(55% + '+ciw+'px)');if($(this).siblings('.teachers').length>0){$(this).siblings('.teachers').css('width','calc(40% - '+ciw+'px)')}}})}});$('.moreinfo').click(function(){$(this).toggleClass('moreinfo_up');$(this).parent().siblings('.content').toggleClass('moreinfo_vis');if($(this).parent().siblings('.content').find('.summary').length>0){if($(this).parent().siblings('.content').hasClass('moreinfo_vis')){scrollHeight=$(this).parent().siblings('.content').find('.summary')[0].scrollHeight;if($(window).width()<1024&&$(this).parent().siblings('.content').find('.summary').children('.courseimage').length>0){scrollHeight=scrollHeight+100}
$(this).parent().siblings('.content').find('.summary').css('max-height',scrollHeight+'px')}else{$(this).parent().siblings('.content').find('.summary').css('max-height','0px')}}
$(this).parent().siblings('.content').find('.expandteachers').toggleClass('expandteachers_vis').toggleClass('expandteachers_novis')});$('.expandteachers').click(function(){$(this).closest('.content').siblings('.info').find('.moreinfo').toggleClass('moreinfo_up');$(this).closest('.content').toggleClass('moreinfo_vis');if($(this).closest('.content').find('.summary').length>0){if($(this).closest('.content').hasClass('moreinfo_vis')){scrollHeight=$(this).closest('.content').find('.summary')[0].scrollHeight;if($(window).width()<1024&&$(this).closest('.content').find('.summary').children('.courseimage').length>0){scrollHeight=scrollHeight+100}
$(this).closest('.content').find('.summary').css('max-height',scrollHeight+'px')}else{$(this).closest('.content').find('.summary').css('max-height','0px')}}
$(this).toggleClass('expandteachers_vis').toggleClass('expandteachers_novis')});$('.show_description').click(function(){$(this).toggleClass('closed_description').toggleClass('opened_description');$('.show_description.closed_description').text('Развернуть все');$('.show_description.opened_description').text('Свернуть все');if($(this).hasClass('opened_description')){$('.coursebox.clearfix').each(function(){$(this).find('.moreinfo').addClass('moreinfo_up');$(this).find('.content').addClass('moreinfo_vis');$(this).find('.expandteachers').removeClass('expandteachers_vis').addClass('expandteachers_novis');if($(this).find('.content').find('.summary').length>0){scrollHeight=$(this).find('.content').find('.summary')[0].scrollHeight;if($(window).width()<1024&&$(this).find('.content').find('.summary').children('.courseimage').length>0){scrollHeight=scrollHeight+100}
$(this).find('.content').find('.summary').css('max-height',scrollHeight+'px')}})}else{$('.coursebox.clearfix').each(function(){$(this).find('.moreinfo').removeClass('moreinfo_up');$(this).find('.content').removeClass('moreinfo_vis');$(this).find('.expandteachers').removeClass('expandteachers_novis').addClass('expandteachers_vis');if($(this).find('.content').find('.summary').length>0){$(this).find('.content').find('.summary').css('max-height','0px')}})}})});
function ann_cen(){if($('#page-course-view-topics').length){if($('.annotation').length){var row_col=$('.annotation');height=row_col.height();if(height<114){$(row_col).parent().addClass('ann_center')}else{(row_col).parent().removeClass('ann_center')}}}}
requirejs(['jquery'],function($){$(document).ready(function(){$('.search-input-wrapper').hover(function(){$(this).addClass('no_hover');setTimeout(function(){$('.search-input-wrapper').removeClass('no_hover')},500)});if($('#page-course-view-topics').length){if($('.annotation_container').length==0){$('li#section-0').addClass('without_ann')}else{$('.annotation_container').hover(function(){$(this).siblings('h1').addClass('annotation_hover')},function(){$(this).siblings('h1').removeClass('annotation_hover')})}
if($('.without_ann').length){$('.without_ann').hover(function(){$(this).closest('#region-main').children('h1').addClass('annotation_hover')},function(){$(this).closest('#region-main').children('h1').removeClass('annotation_hover')})}
$('#region-main h1').hover(function(){$(this).addClass('annotation_hover');$('.without_ann').addClass('after_h1_hover');$('.annotation_container').addClass('after_h1_hover')},function(){$(this).removeClass('annotation_hover');$('.without_ann').removeClass('after_h1_hover');$('.annotation_container').removeClass('after_h1_hover')})}
ann_cen()});$(window).resize(function(){ann_cen()})});
function bread_hei(){$('body').removeClass('bread_two').removeClass('bread_three').removeClass('bread_four').removeClass('bread_five');if($(window).width()>991){var k=Math.round($('.breadcrumb-nav').height()/26);console.log('k='+k);switch(k){case 2:$('body').addClass('bread_two');break;case 3:$('body').addClass('bread_three');break;case 4:$('body').addClass('bread_four');break;case 5:$('body').addClass('bread_five');break}}}
requirejs(['jquery'],function($){$(document).ready(function(){bread_hei()});$(window).resize(function(){bread_hei()})});
requirejs(['jquery'],function($){$(document).ready(function(){var title=$('.userbutton .usertext').text();$('.userbutton .usertext').attr('title',title)})});
function ann_img(){if($('.annotation_container img').length){$('.annotation_container img').each(function(){var cont_width=$('.annotation_container').width()-40;var width=$(this).attr('data-width');if(width>cont_width){$(this).width(cont_width);cont_height=($(this).attr('data-height')/width)*cont_width;$(this).height(cont_height)}else{$(this).width(width);height=$(this).attr('data-height');$(this).height(height)}})}}
requirejs(['jquery'],function($){$(document).ready(function(){if($('#page-course-view-topics').length){if($('.annotation_container').length){if($('.annotation_container img').length){$('.annotation_container img').each(function(){var width=$(this).width();var height=$(this).height();$(this).attr('data-width',width);$(this).attr('data-height',height)})}
ann_img()}}});$(window).resize(function(){if($('#page-course-view-topics').length){if($('.annotation_container').length){ann_img()}}})});
spans=document.querySelectorAll('.correct,.incorrect,.partiallycorrect')
for(i=0;i<spans.length;i++){text=spans[i].innerText
if(text.indexOf(' ;')==-1){continue}
text=text.replaceAll(' ;',';')
spans[i].innerText=text};
require(['core_table/dynamic'],(DynamicTable)=>{function beautyfy_pm(){pluses=document.querySelectorAll('.flexible .fa-plus')
for(i=pluses.length-1;i>=0;i--){pluses[i].setAttribute('aria-hidden','true')
pluses[i].className='fa fa-plus-square-o'}
minuses=document.querySelectorAll('.flexible .fa-minus')
for(i=minuses.length-1;i>=0;i--){minuses[i].setAttribute('aria-hidden','true')
minuses[i].className='fa fa-minus-square-o'}}
beautyfy_pm()
tables=document.querySelectorAll('form[data-table-unique-id]')
if(!tables){return}
tables.forEach(table=>{table.addEventListener(DynamicTable.Events.tableContentRefreshed,e=>{beautyfy_pm()})})});
requirejs(['jquery'],function($){if($('#page-mod-slides-view').length){var AllSlides=0,FullTimer=0,FullElement=null,Height=0,AutoHeight=!1,MustFullScreen=!1,ManualFullscreen=!1,kImage=1,slideNum=1,numSlides=0,iOS=/iPad|iPhone|iPod/.test(navigator.userAgent)&&!window.MSStream,isMobile={Android:function(){return navigator.userAgent.match(/Android/i)},BlackBerry:function(){return navigator.userAgent.match(/BlackBerry/i)},Opera:function(){return navigator.userAgent.match(/Opera Mini/i)},Windows:function(){return navigator.userAgent.match(/IEMobile/i)},any:function(){return(isMobile.Android()||isMobile.BlackBerry()||isMobile.Opera()||isMobile.Windows())}};function setNumbers(k){numSlides=k}
function setKimage(k){kImage=k}
function setHeight(height,setter,fullscreen){fullscreen=fullscreen||!1;var value=parseInt(height);if(setter)
if(value){Height=value}else AutoHeight=!0;if(fullscreen)
return $(window).height()-56;if(AutoHeight)
Height=$(window).height()-410;return Height}
function fullScreenStatus(){return document.fullscreen||document.mozFullScreen||document.webkitIsFullScreen||!1}
function cancelFullScreen(){if(document.exitFullscreen){document.exitFullscreen()}else if(document.mozCancelFullScreen){document.mozCancelFullScreen()}else if(document.webkitCancelFullScreen){document.webkitCancelFullScreen()}}
function supportFullScreen(){var doc=document.documentElement;return('requestFullscreen' in doc)||('mozRequestFullScreen' in doc&&document.mozFullScreenEnabled)||('webkitRequestFullScreen' in doc)}
function setManualFullScreen(element){if(ManualFullscreen){ManualFullscreen=!1;element.setAttribute('class','');$('.jcarousel').jcarousel('reload')}
if(MustFullScreen){if(iOS==!1){initDiv(!0)}
MustFullScreen=!1;element.setAttribute('class','mustfullscreen');ManualFullscreen=!0;$('.jcarousel').jcarousel('reload')}}
function launchFullscreen(element){if(ManualFullscreen){setManualFullScreen(element);return!0};if(element.requestFullScreen){element.requestFullScreen()}else if(element.mozRequestFullScreen){element.mozRequestFullScreen()}else if(element.webkitRequestFullScreen){element.webkitRequestFullScreen()};FullElement=element;MustFullScreen=!0;var setClass=!1;FullTimer=setInterval(function(){if(!fullScreenStatus()){if(iOS==!1){initDiv()}
FullElement.setAttribute('class','');clearTimeout(FullTimer)}else{if(iOS==!1){initDiv(!0)}
MustFullScreen=!1;if(!setClass)element.setAttribute('class','slides-full');setClass=!0};if(MustFullScreen)setManualFullScreen(FullElement)},500)}
function FullScreener(){if(fullScreenStatus()){cancelFullScreen()}else launchFullscreen(document.getElementById('slides'))}
function carouselInit(){$('.jcarousel').on('jcarousel:animateend',function(event,carousel,target,animate){var num=($('.jcarousel-pagination a.active').text());$('.jcarousel-info').text(num+"/"+AllSlides)}).on('jcarousel:create',function(){AllSlides=$('.jcarousel li').get().length;$('.jcarousel-info').text("1/"+AllSlides)}).on('jcarousel:create jcarousel:reload',function(){$('.wrapper-carousel-main li div').height(setHeight(0,!1,fullScreenStatus()||ManualFullscreen));var element=$(this),width=element.innerWidth();element.jcarousel('items').css('width',width+'px')}).jcarousel({animation:{duration:200,easing:'linear',complete:function(){}}});$('.jcarousel-control-prev').on('jcarouselcontrol:active',function(){$(this).removeClass('inactive')}).on('jcarouselcontrol:inactive',function(){$(this).addClass('inactive')}).jcarouselControl({target:'-=1'});$('.jcarousel-control-next').on('jcarouselcontrol:active',function(){$(this).removeClass('inactive')}).on('jcarouselcontrol:inactive',function(){$(this).addClass('inactive')}).jcarouselControl({target:'+=1'});$('.jcarousel-pagination').on('jcarouselpagination:active','a',function(){$(this).addClass('active')}).on('jcarouselpagination:inactive','a',function(){$(this).removeClass('active')}).jcarouselPagination()}
function initInfo(){$(".jcarousel-info").text(slideNum+"/"+numSlides)}
var control_flag=!1;var time=0;function initDiv(fullscreen){fullscreen=fullscreen||!1;var min_div_img=220;var bgImgWidth=1,bgImgHeight=1;var img_slide=$('.jcarousel-wrapper .jcarousel div');var img=new Image;var url_img=$('.jcarousel-wrapper .jcarousel div:first-child').css('background-image').replace(/\S+\.ru(\S+)\S\)/ig,'$1');img.src=url_img;img.onload=function(){bgImgWidth=img.width;bgImgHeight=img.height;img_ratio=bgImgWidth/bgImgHeight;if(fullscreen){$('.jcarousel-control').addClass('full-control');$('.jcarousel-control table').attr('style','');$(window).mousemove(function(){$('.full-control').fadeIn();time=0});$('.full-control').mouseover(function(){control_flag=!0});$('.full-control').mouseout(function(){control_flag=!1});time++;if(control_flag===!1&&(time>6))$('.full-control').fadeOut();img_slide.css({'width':'100%'});if($(window).width()>$(window).height()){img_slide.height($(window).height())}else{var height_slide=img_slide.width()/img_ratio;img_slide.height(height_slide);$('.full-control').show();$('.full-control').css({'bottom':'auto'});control_flag=!0}
$('#slides').css({'max-height':'none'});div_height=$('.jcarousel-wrapper .jcarousel div').height();if(img_ratio<1.5){div_width=div_height*4/3}else{div_width=div_height*16/9}
var img_pagging=(img_slide.width()-div_width)/2;$('.jcarousel-wrapper .jcarousel').css('height',div_height+'px').css('border','0px solid transparent');$('.jcarousel-wrapper .jcarousel div').css('height',div_height+'px');$('.jcarousel-wrapper .jcarousel div').css('width',div_width+'px');$('.jcarousel-wrapper .jcarousel div').css('margin-left',img_pagging+'px')}else{var spanHeight=document.querySelector('#region-main [role="main"] > h2 span');$('.tooltip_coursebox').remove();if(spanHeight.scrollHeight>spanHeight.clientHeight+2){$(spanHeight).parent().append('<div class="tooltip_coursebox"><p>'+$(spanHeight).text()+'</p></div>');if(isMobile.any()){$('.tooltip_coursebox').addClass('touch_after')}else{$('.tooltip_coursebox').addClass('notouch_after')}}
$('#region-main > div[role="main"]').removeClass('region_to_center');$('#slides').removeClass('to_center').css('top','calc(50% + 40px)');window_h=window.innerHeight;$(window).off('mousemove');$('.jcarousel-wrapper .jcarousel div').css('margin-left',0+'px');$('.jcarousel-control').removeClass('full-control');$('.jcarousel-control').attr('style','');var window_height=window_h-$('header').outerHeight()-$('#region-main h2').outerHeight()-$('footer').outerHeight();$('#page').removeClass('blocks_hide');if($(window).width()>1135){height_slide=window_height*0.8-50;width_slide=height_slide*img_ratio;height_slide=height_slide+50}else{k_page=$('#page').height()/$('#page').width();console.log('k_page='+k_page);if(k_page<0.5){$('#page').addClass('blocks_hide');window_height=window_h-$('header').outerHeight();height_slide=window_height*0.9-50;width_slide=height_slide*img_ratio;height_slide=height_slide+50}else{if(k_page>2){width_slide=$('#region-main').width();height_slide=width_slide/img_ratio+250}else{window_height=window_h-$('header').outerHeight();height_slide=window_height*0.9-50;width_slide=height_slide*img_ratio;height_slide=height_slide+50}}};if(width_slide<min_div_img){width_slide=min_div_img;height_slide=(width_slide/img_ratio)}
$('.jcarousel-control table').width(width_slide);$('#slides').width(width_slide);img_slide.height(height_slide);img_slide.width(width_slide);div_width=$('.jcarousel-wrapper .jcarousel div').width();if(img_ratio<1.5){div_height=div_width/4*3}else{div_height=div_width/16*9}
$('.jcarousel-wrapper .jcarousel').css('height',div_height+'px').css('border','0px solid transparent');$('.jcarousel-wrapper .jcarousel div').css('height',div_height+'px');$('#slides').attr('style','width:'+div_width+'px;');$('#region-main > div[role="main"]').addClass('region_to_center');$('#slides').addClass('to_center')}}}
function initDiviOS(){$('#region-main > div[role="main"]').removeClass('region_to_center');$('#slides').removeClass('to_center');$('#page-mod-slides-view #page-content').removeClass('iOS_full_content');$('#slides').removeClass('iOS_full');$('header.fixed-top').removeClass('iOS_full_header');$('header').removeClass('no_vision');$('.cont_bottom_nav').removeClass('no_vision');$('#page-footer').removeClass('no_vision');var min_div_img=220;var bgImgWidth=1,bgImgHeight=1;var img_slide=$('.jcarousel-wrapper .jcarousel div');var img=new Image;var url_img=$('.jcarousel-wrapper .jcarousel div:first-child').css('background-image').replace(/\S+\.ru(\S+)\S\)/ig,'$1');img.src=url_img;img.onload=function(){bgImgWidth=img.width;bgImgHeight=img.height;img_ratio=bgImgWidth/bgImgHeight;if($(window).width()>808)width_slide=($('#region-main').width()*0.8);else width_slide=($('#region-main').width());var intFrameHeight=window.innerHeight;var window_height=intFrameHeight-$('header').outerHeight();if(window.matchMedia('(orientation: landscape)').matches){var page_height=$('#page').height();console.log('page_height='+page_height+', intFrameHeight ='+intFrameHeight+', height='+$(window).height())}
var height_slide=width_slide/img_ratio+50;if(height_slide>(window_height*0.8)){height_slide=window_height*0.8;width_slide=(height_slide*img_ratio);if(width_slide<min_div_img){width_slide=min_div_img;height_slide=(width_slide/img_ratio)}}
$('.jcarousel-control table').width(width_slide);$('#slides').width(width_slide);img_slide.height(height_slide);img_slide.width(width_slide);div_width=$('.jcarousel-wrapper .jcarousel div').width();if(img_ratio<1.5){div_height=div_width/4*3}else{div_height=div_width/16*9}
$('.jcarousel-wrapper .jcarousel').css('height',div_height+'px').css('border','0px solid transparent');$('.jcarousel-wrapper .jcarousel div').css('height',div_height+'px');$('#slides').attr('style','width:'+div_width+'px;');console.log('iOS done');$('#region-main > div[role="main"]').addClass('region_to_center');$('#slides').addClass('to_center')}}
function initDiviOSFull(){if($('#slides').hasClass('ios-background')){$('#region-main > div[role="main"]').removeClass('region_to_center');$('#slides').removeClass('to_center');var bgImgWidth=1,bgImgHeight=1;var img_slide=$('.jcarousel-wrapper .jcarousel div');var img=new Image;var url_img=$('.jcarousel-wrapper .jcarousel div:first-child').css('background-image').replace(/\S+\.ru(\S+)\S\)/ig,'$1');img.src=url_img;img.onload=function(){bgImgWidth=img.width;bgImgHeight=img.height;img_ratio=bgImgWidth/bgImgHeight;$('.jcarousel-control table').attr('style','');var intFrameHeight=window.innerHeight;$(window).mousemove(function(){$('.full-control').fadeIn();time=0});$('.full-control').mouseover(function(){control_flag=!0});$('.full-control').mouseout(function(){control_flag=!1});time++;if(control_flag===!1&&(time>6))$('.full-control').fadeOut();img_slide.css({'width':'100%'});$('#page-mod-slides-view #page-content').addClass('iOS_full_content');$('#slides').addClass('iOS_full');$('#slides').css('width','100%');$('header.fixed-top').addClass('iOS_full_header');$('header').addClass('no_vision');$('footer').addClass('no_vision');$('.jcarousel-wrapper .jcarousel div').css('touch-action','none');if($(window).width()>$(window).height()){img_slide.height(intFrameHeight);$('.full-control').show();$('.full-control').css({'bottom':'auto'});control_flag=!0;var div_height_full=intFrameHeight-55;if(img_ratio<1.5){div_width_full=div_height_full*4/3}else{div_width_full=div_height_full*16/9}
$('.jcarousel-wrapper .jcarousel').css('height',(div_height_full+0)+'px').css('padding-top',1+'px');$('.jcarousel-wrapper .jcarousel div').css('height',div_height_full+'px')}else{var height_slide=img_slide.width()/img_ratio;img_slide.height(height_slide);$('.full-control').show();$('.full-control').css({'bottom':'auto'});control_flag=!0;div_width_full=$('.jcarousel-wrapper .jcarousel div').width();if(img_ratio<1.5){div_height_full=div_width_full/4*3}else{div_height_full=div_width_full/16*9}
$('.jcarousel-wrapper .jcarousel').css('height',(div_height_full+1)+'px');$('.jcarousel-wrapper .jcarousel div').css('height',div_height_full+'px');div_width_full=$('.jcarousel-wrapper .jcarousel div').width();console.log('FullScreen vertical done'+', div_width='+div_width_full+', (window).width()'+$(window).width())}}}else{$('#slides').attr('style','');$('#slides').css('width',width_slide+'px');$('.jcarousel-wrapper .jcarousel div').css('touch-action','auto');$('.jcarousel-wrapper .jcarousel div').css('padding-top',0+'px')
initDiviOS();console.log('return FullScreen done')}}
$(document).ready(function(){$('.closemanual').click(function(){FullScreener()});$(document).bind('keyup',function(e){if(e.keyCode==27)
if(ManualFullscreen)
FullScreener()});$('#region-main [role="main"] > h2').wrapInner('<span></span>');$('#region-main [role="main"] > h2').click(function(){$('.touch_after').addClass('clicked')});$(document).mouseup(function(e){var div=$('.touch_after');if(!div.is(e.target)){div.removeClass('clicked')}});$('#dLabel').click(function(){$(this).toggleClass('show_download')});$(document).mouseup(function(e){var div=$('#dLabel');if(!div.is(e.target)&&div.siblings(e.target)){div.removeClass('show_download')}});if(iOS==!0){initDiviOS();window.addEventListener('load',function(){var full_push=document.getElementById('fullscreen')
full_push.addEventListener('touchend',function(e){var touchobj=e.changedTouches[0]
$('#slides').toggleClass('ios-background');initDiviOSFull();e.preventDefault()},!1)},!1)}else{$("#fullscreen").click(function(){FullScreener()});initDiv()}
$('.jcarousel-control-next').click(function(){if(slideNum<numSlides){$(".jcarousel-wrapper .jcarousel div[alt='"+slideNum+"']").fadeTo(900,0,"linear");hide_div=slideNum;slideNum++;$(".jcarousel-wrapper .jcarousel div[alt='"+slideNum+"']").fadeTo(1,0,"linear").show(1).fadeTo(900,1,"linear");$(".jcarousel-wrapper .jcarousel div[alt='"+hide_div+"']").fadeTo(1,0,"linear").delay(900).hide(1).fadeTo(1,1);initInfo();$(this).removeClass("inactive")};if(slideNum==numSlides)
$(this).addClass("inactive");if(slideNum>1){$('.jcarousel-control-prev').removeClass("inactive")}else $('.jcarousel-control-prev').addClass("inactive");return!1});$('.jcarousel-control-prev').click(function(){if(slideNum>1){$(".jcarousel-wrapper .jcarousel div[alt='"+slideNum+"']").fadeTo(900,0,"linear");hide_div=slideNum;slideNum--;$(".jcarousel-wrapper .jcarousel div[alt='"+slideNum+"']").fadeTo(1,0,"linear").show(1).fadeTo(900,1,"linear");$(".jcarousel-wrapper .jcarousel div[alt='"+hide_div+"']").fadeTo(1,0,"linear").delay(900).hide(1).fadeTo(1,1);initInfo();$(this).removeClass("inactive")};if(slideNum==1)
$(this).addClass("inactive");if(slideNum<numSlides){$('.jcarousel-control-next').removeClass("inactive")}else $('.jcarousel-control-next').addClass("inactive");return!1});$(window).resize(function(){if(iOS==!1){initDiv()}else{$("#slides").removeClass('ios-background');initDiviOS()}})
if(navigator.userAgent.match(/msie/i)||navigator.userAgent.match(/trident/i)){$('a#fullscreen').hide()}})}});
function compute(){video=document.getElementById('videobg');width_video=height_video=k_size=h2_height=footer_height=top_height=al=pageHeight=window_h=0;width_video=video.videoWidth;height_video=video.videoHeight;k_size=width_video/height_video;h2_height=$('h2').innerHeight();footer_height=$('#page-footer').innerHeight();top_height=$('nav.fixed-top').innerHeight();if($('div').is('.alert')==!0){al=$('div.alert').innerHeight()}else{al=0}
pageHeight=window.innerHeight-footer_height-top_height-al-2;window_h=window.innerHeight;window_w=$('#region-main-box').width();pageHeight=pageHeight-h2_height;window_h=window_h-h2_height-footer_height-top_height;k_window=window_w/window_h;var mql=window.matchMedia("(orientation: portrait)");if(mql.matches){w_video=window_w-40;$('.container-video').css('max-width',w_video+'px');h_video=w_video/k_size;$('.container-video').css('max-height',h_video+'px');$('.container-video').css('height',h_video+'px')}else{if($(window).width()>809){if(k_size>2.5){w_video=window_w*0.85-46;$('.container-video').css('max-width',w_video+'px');h_video=w_video/k_size;$('.container-video').css('max-height',h_video+'px');$('.container-video').css('height',h_video+'px')}
if(k_size>1.6&&k_size<2){w_video=window_w*0.6-46;$('.container-video').css('max-width',w_video+'px');h_video=w_video/k_size;$('.container-video').css('max-height',h_video+'px');$('.container-video').css('height',h_video+'px')}
if(k_size>1.2&&k_size<1.5){w_video=window_w*0.5-46;$('.container-video').css('max-width',w_video+'px');h_video=w_video/k_size;$('.container-video').css('max-height',h_video+'px');$('.container-video').css('height',h_video+'px')}}else{h_video=window_h*0.9+footer_height-20;$('.container-video').css('max-height',h_video+'px');$('.container-video').css('height',h_video+'px');w_video=h_video*k_size;$('.container-video').css('max-width',w_video+'px');pageHeight=pageHeight+footer_height}}};require(['jquery'],function($,controller){if($('#page-mod-videofile-view').length){$(document).ready(function(){window.onload=function(){compute()};document.getElementById('videobg').onloadedmetadata=function(e){compute()};$(window).resize(function(){compute();if(fullscreen_flag==!0){$('.container-video').css('max-width','none');$('.container-video').css('max-height','none')}});var fullscreen_flag=!1;$('#fullscreen-button').click(function(){var elem=document.getElementById("slide-video");if(!fullscreen_flag){if(elem.requestFullscreen){elem.requestFullscreen()}else if(elem.mozRequestFullScreen){elem.mozRequestFullScreen()}else if(elem.webkitRequestFullscreen){elem.webkitRequestFullscreen()}else if(elem.msRequestFullscreen){elem.msRequestFullscreen()};fullscreen_flag=!0}else{if(document.cancelFullScreen){document.cancelFullScreen()}else if(document.webkitCancelFullScreen){document.webkitCancelFullScreen()}else if(document.mozCancelFullScreen){document.mozCancelFullScreen()}else if(document.msExitFullscreen){document.msExitFullscreen()}
fullscreen_flag=!1;compute()}});if(document.addEventListener){document.addEventListener('webkitfullscreenchange',exitHandler,!1);document.addEventListener('mozfullscreenchange',exitHandler,!1);document.addEventListener('fullscreenchange',exitHandler,!1);document.addEventListener('MSFullscreenChange',exitHandler,!1)}
function exitHandler(){if(!document.webkitIsFullScreen&&!document.mozFullScreen&&!document.msFullscreenElement){fullscreen_flag=!1;compute()}}})}});
requirejs(['jquery'],function($){$(document).ready(function(){const navBar=$('.navbar-collapse .navbar-nav').first();let userName=$('.usertext').filter(':visible'),userFull=userName.text();let navFullitem=navBar.children(),navFullWidth=navBar.width(),windowWidth=$(window).width();function adaptationUser(selector){let str=selector.text();str=str.split(/\s+/).map((w,i)=>i?w.substring(0,1).toUpperCase()+'.':w).join(' ');selector.html(str)};if($(window).width()<1265){adaptationUser(userName)}else if($(window).width()>1265){userName.html(userFull)}
if(navBar.height()>=38){negativeWidthChange()}
$(window).resize(function(){userName=$('.usertext').filter(':visible');if($(window).width()<1265){adaptationUser(userName)}else{userName.html(userFull)}
if($('body').width()>=992){$('.dark_window').remove();$('.burg-menu').removeClass('show-menu').addClass('hide-menu');$('body').removeClass('no_overflow')}
widthCheck();$('.drop-down-menu').hide();$('.drop-down-menu').css({'left':navBar.children().last().offset().left})});$('.search-input-wrapper').hover(function(){if(navBar.height()>=38){negativeWidthChange()}});function negativeWidthChange(){let dropMas=[];if(!navBar.children().hasClass('nav-btn')&&!$('body').children().hasClass('nav-btn')){navBar.append('<li class="nav-btn"><a id="drop-down-btn" class="nav-link"></li>');$('body').append('<section class="drop-down-menu"></section>')}
for(let i=navBar.children('.nav-item').length-1;i>=0;i--){if(navBar.height()>=38){$('.drop-down-menu').append(navBar.children('.nav-item').eq(i))}}
$('.drop-down-menu').css({'left':navBar.children().last().offset().left})};function positiveWidthChange(){for(let i=$('.drop-down-menu').children().length-1;i>=0;i--){navBar.append($('.drop-down-menu').children().eq(i))
if(navBar.height()>=38){negativeWidthChange()}else{$('.nav-btn').remove();navBar.append('<li class="nav-btn"><a id="drop-down-btn" class="nav-link"></li>')}}
if($('.drop-down-menu').children().length==0){$('.drop-down-menu').remove()
$('.nav-btn').remove()}}
function widthCheck(){setTimeout(function(){windowWidth=$(window).width()},500);if($(window).width()>windowWidth){if(navBar.height()<=38){positiveWidthChange()}else{negativeWidthChange()}}else{if(navBar.height()>=38){negativeWidthChange()}else{positiveWidthChange()}}};$('body').on('click','.nav-btn',function(){if($('.drop-down-menu').is(':hidden')){$('.drop-down-menu').show()}else{$('.drop-down-menu').hide()}})
$('.search-line').click(function(){if($(window).width()<1000){if($('.search-input-nav').find('.search-input-form').is(':hidden')){$('.search-line').addClass('active');$('.search-input-form').fadeIn();$(this).find('.form-control').focus()}}})
$('.btn_burg-menu').click(function(){if(!$('.burg-menu').hasClass('show-menu')){$('.burg-menu').removeClass('hide-menu').addClass('show-menu');$('body').addClass('no_overflow');$('.burg-menu').parent().append('<div class="dark_window"><i class="fa fa-times dark_window_close" aria-hidden="true"></i></div>')}})});$(document).click(function(e){if(!$('.search-line').is(e.target)&&$('.search-line').has(e.target).length===0){$('.search-line').removeClass('active');$('.search-line').find('.search-input-form').fadeOut()}
if($('.dark_window').is(e.target)||$('.dark_window_close').is(e.target)){$('.burg-menu').removeClass('show-menu').addClass('hide-menu');$('.dark_window').remove();$('body').removeClass('no_overflow')}
if(!$('.drop-down-menu').is(e.target)&&$('.nav-btn').has(e.target).length===0){$('.drop-down-menu').hide()}})
$('.drawer .text-dark').click(function(e){e.preventDefault()})})